export const FETCH_COLLECTION = "FETCH_COLLECTION";
export const FETCH_COLLECTION_INIT = "FETCH_COLLECTION_INIT";
export const FETCH_COLLECTION_SUCCESS = "FETCH_COLLECTION_SUCCESS";
export const FETCH_COLLECTION_ERROR = "FETCH_COLLECTION_ERROR";

export const INVALIDATE_COLLECTION = "INVALIDATE_COLLECTION";
