export const FETCH_MULTIPLE_STORIES = "FETCH_MULTIPLE_STORIES";

export const FETCH_STORY = "FETCH_STORY";
export const FETCH_STORY_INIT = "FETCH_STORY_INIT";
export const FETCH_STORY_SUCCESS = "FETCH_STORY_SUCCESS";
export const FETCH_STORY_ERROR = "FETCH_STORY_ERROR";
