export const SAVE_STORY = "SAVE_STORY";
export const DELETE_STORY = "DELETE_STORY";

export const ADD_COLLECTION = "ADD_COLLECTION";
export const REMOVE_COLLECTION = "REMOVE_COLLECTION";

export const UPDATE_THEME = "UPDATE_THEME";
