export const SAVE_STORY = "SAVE_STORY";
export const DELETE_STORY = "DELETE_STORY";

export const ADD_COLLECTION = "ADD_COLLECTION_TO_VIEW";
export const REMOVE_COLLECTION = "REMOVE_COLLECTION_FROM_VIEW";
